apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: "2021-03-20T19:09:29Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      common.k8s.elastic.co/type: elasticsearch
      elasticsearch.k8s.elastic.co/cluster-name: quickstart
      elasticsearch.k8s.elastic.co/statefulset-name: quickstart-es-default
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:common.k8s.elastic.co/type: {}
            f:elasticsearch.k8s.elastic.co/cluster-name: {}
            f:elasticsearch.k8s.elastic.co/statefulset-name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"148186ef-9da6-4ca9-b4bb-b3fb16977f27"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-03-20T19:09:29Z"
    name: elasticsearch-data-quickstart-es-default-0
    namespace: default
    ownerReferences:
    - apiVersion: elasticsearch.k8s.elastic.co/v1
      blockOwnerDeletion: false
      controller: true
      kind: Elasticsearch
      name: quickstart
      uid: 148186ef-9da6-4ca9-b4bb-b3fb16977f27
    resourceVersion: "301487"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-quickstart-es-default-0
    uid: a83ffe1b-cfa4-4e47-ae5c-0ca99a7b57e3
  spec:
    storageClassName: nfs-client
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
